[__config__]
oldver = "old_ver.txt"
newver = "new_ver.txt"

[netfilter-fullconenat-dkms-git]
source = "github"
github = "Chion82/netfilter-full-cone-nat"

[go-stun-git]
source = "github"
github = "ccding/go-stun"

[canta-kde-git]
source = "github"
github = "vinceliuice/Canta-kde"

